Migration to Angular 15 (#1257)
* Migrationn to Angular 15

* Updates @angular-eslint to v15

* Updated version to 15

* Updates the Angular Material to v15.

* ng generate @angular/material:mdc-migration

* npm i @angular/flex-layout

* `FloatLabel` input can be either set to always or auto

* `o-slider`: Removed invert, tickInternal and vertical property

* `<mat-placeholder>` has been deprecated, use `<mat-label>` instead

* `MatListAvatarCssMatStyler` has been deprecated

* Set prefix in angular.json

* Added theming

* Revert migration material v15

* Updated package-lock

* Updated Angular Material to version 15

* ng generate @angular/material:mdc-migration

* Move ontimize-web-ngx-theming to theming folder

* typography level  `$input` is not supported

* Legacy and standard appearance is not supported

* Updated `build-styles` scro`t

* Updated peerDependencies

* Replaced mat.font-size($typography, title); to mat.font-size($typography, headline-5);

* Resolved breaking changes in typography levels

* Emit the theme config and typography in custom and native components

* Changes required by theme structure (color, typography,density) change

* Aligned image in o-button with image

* feat: updated workflows (#1267)

* o-app-sidenav: Fixed mdc-migration

* mdc-migration: Checkbox touch targets to 16px or 15px instead of 40px

* mdc: set height icon button to 32px

* mdc: $body-1 set font size to 13px

* Add release candidate support into workflows (#1269)

* feat: add RC support

* chore: main branch of 15.x

* Updated zone, rxjs and tslib versions

* RxJS 6.x to 7.x : Resolving breaking changes

* Fixed Poppins fonts only was loading in ontimize-lite

* Updated function fashion-mat-dark-theme and fashion-mat-light-theme

* Updated version to 15.0.0-SNAPSHOT-0

* list(mdc-migration): resolving styles breaking change

* mdc: Migration o-table-visible-columns-dialog

* mdc: Resolving breaking changes Dialog

* mdc: Resolving breaking changes in o-table-export-dialog

* mdc: Resolving breaking change in mat-dialog

* TODO(mdc-migration) in o-mat-menu

* mdc-migration: o-dual-list-selector

* TODO(mdc-migration): remove appearance legacy

* TODO (mdc-migration): o-table-quickfilter

* New input `subscriptSizing` in input components

* Renamed  subscriptSizing with subscript-sizing

* Revert "`FloatLabel` input can be either set to always or auto"

This reverts commit 08bafa7c4af242f466c05fc7435953e5a37ee6b3.

* TODO mdc: Resolving breaking in input

* Replace matLine by matListItemTitle, matListItemLine in o-table

* TODO mdc-migration in o-combo

* Updated package-lock

* [Migration] Changes from 8.10.0 into 15.0.0 (#1273)

* Merge pull request #1176 from OntimizeWeb/release/8.11.0
Release 8.11.0

* Merge pull request #133 from OntimizeWeb/hotfix/8.5.2 and Merge pull request #126 from OntimizeWeb/hotfix/8.5.1

* Merged ontimize-web-ngx-theming@8.5.0 changes

* Merge pull request #1181 from OntimizeWeb/hotfix/8.11.1 Hotfix 8.11.1

* Merge pull request #1190 from OntimizeWeb/hotfix/8.11.2
Hotfix 8.11.2

* Merge pull request #1200 from OntimizeWeb/sync/release-8.11.3-to-develop

Sync release 8.11.3 to develop

* Merge pull request #1217 from OntimizeWeb/release/8.12.0
Release 8.12.0

* Merge pull request #1227 from OntimizeWeb/sync/release-8.12.1-to-develop

Sync release 8.12.1 to develop

* Merge pull request #1232 from OntimizeWeb/hotfix/8.12.2
Hotfix 8.12.2

* Merge pull request #1255 from OntimizeWeb/release/8.13.0
Release 8.13.0

* Merge pull request #1271 from OntimizeWeb/release/8.14.0
Release 8.14.0

* Updated version to 15.0.0-SNAPSHOT-1

* Remove this unused import of 'DEFAULT_OUTPUTS_O_TABLE_CELL_EDITOR'.

* 'subscribe' is deprecated. Instead of passing separate callback arguments, use an observer argument

---------

Co-authored-by: Daniel Graña Cousido <daniel.grana@imatia.com>

* TODO(mdc-migration) in o-button-toggle

* TODO(mdc-migration): Removed unused  styles

* TODO(mdc-migration): o-search-input

* Improved icon button styles

* Improved o-table-quickfilter styles

* TODO(mdc-migration): o-list-picker

* o-search-input: New input label

* TODO(mdc-migration):ontimize.scss

* TODO(mdc-migration): input.theme.scss

* TODO(mdc-migration):o-checkbox

* TODO(mdc-migration):o-phone-input

* TODO mdc-migration: o-list

* theming: Fixed mixin o-mat-light-theme and o-mat-dark-theme and

* o-form-layout-tabgroup-options: New input stretch-tabs

* todo(mdc-migration): o-form-layout-tabgroup

* TODO(mdc-migration): o-radio

* Fixed checkbox styles in o-table

* TODO(mdc-migration): o-table

* Fixed code smell

* Fixed the icon not displaying correctly on the buttons.

* Fixed codesmells

* Added styles to mat-paginanator

* o-table:Fixed sort button appears next to the text in the header

* [15.x.x] Replace InputConverter by NumberInputConverter and BooleanInputConverter  (#1275)

* Fixed  error TS2322: Type '"never"' is not assignable to type 'FloatLabelType'.

* Uninstalled reflect-metadata

* Fixed error TS2345: Argument of type 'void' is not assignable to parameter of type 'Event'.

* Fixed error TS2445: Property 'openedSrc' and 'closedSrc' is protected and only accessible within class 'OAppSidenavImageComponent' and its subclasses.

* Removed @OComponent

* Updated version to 15.0.0-SNAPSHOT-2

* Replaced deprecated @InputConverter with @BooleanInputConverter and @NumberInputConverter

* New decorator BooleanInputConverter and NumberInputConverter

* Updated tsconfig.json

* Removed reflect-metadata dependencie

* Resolved codesmell

* Removed unnecesary decorator about queryOnChangeEventType

* Removed unnecessary @BooleanInputConverter decorator

* Updated tsconfg

* Fixed duplicated code

* Fixed height and width in mat icon button into prefix or suffix

* Fixed font color  in active tab

* o-slider:mdc-migration

* Fixed density in checkbox

* o-table: Fixed select all header not show correctly

* o-table-visible-columns: the icon drag_handle doesnot show correctly

* Fixed styles in o-list-item-card

* Fixe styles in mat-list

* o-time-input: fixed styles in clear button

* feat: workflow beta version support (#1279)

* date-picker:Fixed button styles

* radio-button: lite styles

* implatform: fixed selector in buttons styles

* Created appearance service (#1278)

* created appearance service

* deleted comments

* added comments

* updated localstorage reference

* added isDarkMode

* modified storage

* updated CHANGELOG and README

* modified note

* updated README and CHANGELOG

---------

Co-authored-by: Daniel Graña Cousido <daniel.grana@imatia.com>
Co-authored-by: tomfacal <88186642+tomfacal@users.noreply.github.com>