[core] Migration to 14.x.x (#1236)
* Migration to Angular 14

* Uninstalled @angular/flex-layout

* Updated Eslint to 14

* Updated Angular Material to version 14

* npm i @angular/flex-layout@14.0.0-beta.40

* Updated  peerDependencies

* Fixing error in MatIconTestingModule

* Use MatSelectionListChange.options rather than MatSelectionListChange.option.

* Fixed error Uncaught TypeError: Reflect.getMetadata is not a function

* Removed unused imports

* Updated fake-icon-registry

* Removed duplicated code

* Removed this unused import